# Generated by Django 4.2.5 on 2023-10-15 12:15

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0005_rename_gridrefer_pinemarten_gridrefere'),
    ]

    operations = [
        migrations.CreateModel(
            name='PineMartens',
            fields=[
                ('OBJECTID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TAXON_LATI', models.CharField(max_length=75)),
                ('SAMPLE_SPA', models.CharField(max_length=40)),
                ('SURVEY_NAM', models.CharField(max_length=100)),
                ('SAMPLE_YEA', models.DecimalField(decimal_places=11, max_digits=19)),
                ('DatasetTit', models.CharField(max_length=254)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('SiteName', models.CharField(max_length=254)),
                ('GridRefere', models.CharField(max_length=254)),
                ('Source', models.CharField(max_length=254)),
                ('RecordDate', models.DateField()),
                ('x_coord_IG', models.BigIntegerField()),
                ('y_coord_IG', models.BigIntegerField()),
                ('Input_file', models.CharField(max_length=100)),
                ('Source_file', models.CharField(max_length=100)),
                ('geometry', django.contrib.gis.db.models.fields.PointField(srid=4326)),
            ],
        ),
        migrations.DeleteModel(
            name='PineMarten',
        ),
    ]
