# Generated by Django 4.2.5 on 2023-10-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0008_alter_pinemartens_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinemartens',
            name='GridRefere',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pinemartens',
            name='Input_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinemartens',
            name='SiteName',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pinemartens',
            name='Source',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='pinemartens',
            name='Source_file',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
