# Generated by Django 4.2.5 on 2023-10-15 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0009_alter_pinemartens_gridrefere_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinemartens',
            name='SAMPLE_SPA',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pinemartens',
            name='SURVEY_NAM',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='pinemartens',
            name='TAXON_LATI',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
    ]
