# Generated by Django 4.2.5 on 2023-10-16 20:26

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0012_alter_pinemartens_sample_yea'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pinemartens',
            name='geometry',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
