# Generated by Django 4.2.5 on 2023-10-14 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PointDistribution',
            fields=[
                ('OBJECTID', models.BigAutoField(primary_key=True, serialize=False)),
                ('TAXON_LATI', models.CharField(max_length=75)),
                ('SAMPLE_SPA', models.CharField(max_length=40)),
                ('SURVEY_NAM', models.CharField(max_length=100)),
                ('SAMPLE_YEA', models.DecimalField(decimal_places=11, max_digits=19)),
                ('DatasetTit', models.CharField(max_length=254)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('SiteName', models.CharField(max_length=254)),
                ('GridReference', models.CharField(max_length=254)),
                ('RecordDate', models.DateField()),
                ('x_coord_IG', models.BigIntegerField()),
                ('y_coord_IG', models.BigIntegerField()),
                ('Input_file', models.CharField(max_length=100)),
                ('Source', models.CharField(max_length=100)),
            ],
        ),
    ]
