# Generated by Django 4.2.5 on 2023-10-15 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment1', '0004_pinemarten_delete_pointdistribution'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinemarten',
            old_name='GridRefer',
            new_name='GridRefere',
        ),
    ]
